#!/bin/sh
#
# tlib - testing libctags.a via mini-geany
#
# Copyright (C) 2019 Masatake YAMATO
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e

MINI_GEANY=$1
expected=$2
actual=$3
VG=$4

VALGRIND=
if test "${VG}" = 1; then
   VALGRIND="valgrind --leak-check=full"
fi

${VALGRIND} ${MINI_GEANY} > ${actual}
echo "${VALGRIND} ${MINI_GEANY} output:"
cat ${actual}
N=$(sed -n -e 's/^Number of all parsers is: \([0-9]*\)$/\1/p' ${actual})

test "$N" -gt 0

sed -i -e '/^Number of all parsers is: [0-9]*$/d' ${actual}

echo "comparing with expected output:"
diff -uN --strip-trailing-cr ${expected} ${actual} && rm ${actual}

exit 0
