version: 2
jobs:
   fedora_bmake:
     working_directory: ~/universal-ctags
     docker:
       - image: docker.io/fedora:latest
     steps:
       - run:
           name: Install Git and Gdb
           command: |
             dnf -y install git gdb || :
       - checkout
       - run:
           name: Install build tools
           command: |
             dnf -y install gcc automake autoconf pkgconfig bmake aspell-devel aspell-en libxml2-devel jansson-devel libyaml-devel findutils || :
       - run:
           name: Build
           command: |
             bash ./autogen.sh
             MAKE=bmake ./configure --enable-debugging
             bmake -j 2
       - run:
           name: Test
           command: |
             MAKE=bmake bmake check roundtrip CIRCLECI=1
   centos_make:
     working_directory: ~/universal-ctags
     docker:
       - image: docker.io/centos:latest
     steps:
       - run:
           name: Install Git
           command: |
             yum -y install git || :
       - checkout
       - run:
           name: Install build and test tools
           # TODO: enable spell checker
           command: |
              rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm \
              && yum -y install epel-release \
              && yum -y install gcc automake autoconf pkgconfig make \
                 libxml2-devel jansson-devel libyaml-devel findutils \
                 puppet-agent-5.5.6-1.el7 jq || :
       - run:
           name: Build
           command: |
             bash ./autogen.sh
             ./configure --enable-debugging
             make -j 2
       - run:
           name: Test
           command: |
             make verify-units-inputs check roundtrip CIRCLECI=1 PATH=/opt/puppetlabs/bin:$PATH

workflows:
  version: 2
  build_and_test:
    jobs:
      - fedora_bmake
      - centos_make
