/*-----------------------------------------------------------------------------
 * This file is autogenerated from config.h.in.cmake during the CMake
 * configuration of your project. If you need to make changes edit the original
 * file NOT THIS FILE.
 * ---------------------------------------------------------------------------*/
#ifndef _CONFIG_H_
#define _CONFIG_H_
#cmakedefine HAVE_DIRECT_H @HAVE_DIRECT_H@
#cmakedefine HAVE_DIRENT_H @HAVE_DIRENT_H@
#cmakedefine HAVE_FCNTL_H @HAVE_FCNTL_H@
#cmakedefine HAVE_IO_H @HAVE_IO_H@
#cmakedefine HAVE_STAT_H @HAVE_STAT_H@
#cmakedefine HAVE_TYPES_H @HAVE_TYPES_H@
#cmakedefine HAVE_UNISTD_H @HAVE_UNISTD_H@
#cmakedefine HAVE_SYS_DIR_H @HAVE_SYS_DIR_H@
#cmakedefine HAVE_SYS_STAT_H @HAVE_SYS_STAT_H@
#cmakedefine HAVE_SYS_TYPES_H @HAVE_SYS_TYPES_H@
#cmakedefine HAVE_SYS_WAIT_H @HAVE_SYS_WAIT_H@
#cmakedefine HAVE_STDBOOL_H @HAVE_STDBOOL_H@
#cmakedefine HAVE_REGCOMP @HAVE_REGCOMP@
#cmakedefine PACKAGE_VERSION @PACKAGE_VERSION@
#cmakedefine HAVE_LIBXML @HAVE_LIBXML@
#cmakedefine HAVE_LIBYAML @HAVE_LIBYAML@
#cmakedefine HAVE_JANSSON @HAVE_JANSSON@
#cmakedefine HAVE_SECCOMP @HAVE_SECCOMP@
#cmakedefine EXTERNAL_SORT @EXTERNAL_SORT@
#cmakedefine HAVE_SETENV @HAVE_SETENV@
#cmakedefine HAVE_PUTENV @HAVE_PUTENV@
#cmakedefine HAVE_ICONV @HAVE_ICONV@
#cmakedefine HAVE_MKSTEMP @HAVE_MKSTEMP@
#endif
