/*
 *
 *  Copyright (c) 2015, Red Hat, Inc.
 *  Copyright (c) 2015, Masatake YAMATO
 *
 *  Author: Masatake YAMATO <yamato@redhat.com>
 *
 *   This source code is released for free distribution under the terms of the
 *   GNU General Public License version 2 or (at your option) any later version.
 *
 */

#include "general.h"  /* must always come first */
#include "debug.h"
#include "main.h"
#include "options.h"
#include "routines.h"
#include "xtag.h"

#include <string.h>
#include <ctype.h>

typedef struct sXtagObject {
	xtagDefinition *spec;
	langType language;
	xtagType sibling;
} xtagObject;

static bool isPseudoTagsEnabled (xtagDefinition *pspec CTAGS_ATTR_UNUSED)
{
	return ! isDestinationStdout ();
}

static xtagDefinition xtagDefinitions [] = {
	{ true, 'F',  "fileScope",
	  "Include tags of file scope" },
	{ false, 'f', "inputFile",
	  "Include an entry for the base file name of every input file"},
	{ false, 'p', "pseudo",
	  "Include pseudo tags",
	  isPseudoTagsEnabled},
	{ false, 'q', "qualified",
	  "Include an extra class-qualified tag entry for each tag"},
	{ false, 'r', "reference",
	  "Include reference tags"},
	{ false, 'g', "guest",
	  "Include tags generated by guest parsers"},
};

static unsigned int       xtagObjectUsed;
static unsigned int       xtagObjectAllocated;
static xtagObject* xtagObjects;

static xtagObject* getXtagObject (xtagType type)
{
	Assert ((0 <= type) && (type < xtagObjectUsed));
	return (xtagObjects + type);
}

extern xtagDefinition* getXtagDefinition (xtagType type)
{
	Assert ((0 <= type) && (type < xtagObjectUsed));

	return getXtagObject (type)->spec;
}

typedef bool (* xtagPredicate) (xtagObject *pdesc, langType language, const void *user_data);
static xtagType  getXtagTypeGeneric (xtagPredicate predicate, langType language, const void *user_data)
{
	static bool initialized = false;
	int i;

	if (language == LANG_AUTO && (initialized == false))
	{
		initialized = true;
		initializeParser (LANG_AUTO);
	}
	else if (language != LANG_IGNORE && (initialized == false))
		initializeParser (language);

	for (i = 0; i < xtagObjectUsed; i++)
	{
		if (predicate (xtagObjects + i, language, user_data))
			return i;
	}
	return XTAG_UNKNOWN;
}

static bool xtagEqualByLetter (xtagObject *pdesc, langType language CTAGS_ATTR_UNUSED,
							   const void *user_data)
{
	return (pdesc->spec->letter == *((char *)user_data))? true: false;
}

extern xtagType  getXtagTypeForLetter (char letter)
{
	return getXtagTypeGeneric (xtagEqualByLetter, LANG_IGNORE, &letter);
}

static bool xtagEqualByNameAndLanguage (xtagObject *pdesc, langType language, const void *user_data)
{
	const char* name = user_data;

	if ((language == LANG_AUTO || pdesc->language == language)
		&& (strcmp (pdesc->spec->name, name) == 0))
		return true;
	else
		return false;
}

extern xtagType  getXtagTypeForNameAndLanguage (const char *name, langType language)
{
	return getXtagTypeGeneric (xtagEqualByNameAndLanguage, language, name);
}


#define PR_XTAG_WIDTH_LETTER     7
#define PR_XTAG_WIDTH_NAME      22
#define PR_XTAG_WIDTH_ENABLED   7
#define PR_XTAG_WIDTH_LANGUAGE  16
#define PR_XTAG_WIDTH_DESC      30

#define PR_XTAG_STR(X) PR_XTAG_WIDTH_##X
#define PR_XTAG_FMT(X,T) "%-" STRINGIFY(PR_XTAG_STR(X)) STRINGIFY(T)
#define MAKE_XTAG_FMT(LETTER_SPEC)		\
	PR_XTAG_FMT (LETTER,LETTER_SPEC)	\
	" "					\
	PR_XTAG_FMT (NAME,s)			\
	" "					\
	PR_XTAG_FMT (ENABLED,s)			\
	" "					\
	PR_XTAG_FMT (LANGUAGE,s)		\
	" "					\
	PR_XTAG_FMT (DESC,s)			\
	"\n"

static void printXtag (xtagType i)
{
	unsigned char letter = getXtagDefinition (i)->letter;
	langType lang;
	const char *language;
	const char *desc;

	if (letter == NUL_XTAG_LETTER)
		letter = '-';


	lang = getXtagObject (i)->language;

	if (lang == LANG_IGNORE)
		language = "NONE";
	else
		language = getLanguageName (lang);

	desc = getXtagDefinition (i)->description;
	if (!desc)
		desc = "NONE";

	printf((Option.machinable? "%c\t%s\t%s\t%s\t%s\n": MAKE_XTAG_FMT(c)),
	       letter,
		   getXtagName (i),
	       getXtagDefinition (i)->enabled? "TRUE": "FALSE",
		   language,
	       desc);
}

extern void printXtags (int language)
{
	unsigned int i;

	if (Option.withListHeader)
		printf ((Option.machinable? "%s\t%s\t%s\t%s\t%s\n": MAKE_XTAG_FMT(s)),
				"#LETTER", "NAME", "ENABLED", "LANGUAGE", "DESCRIPTION");

	for (i = 0; i < xtagObjectUsed; i++)
	{
		if (language == LANG_AUTO || getXtagOwner (i) == language)
			printXtag (i);
	}

}

extern bool isXtagEnabled (xtagType type)
{
	xtagDefinition* spec = getXtagDefinition (type);

	Assert (spec);

	if (spec->isEnabled)
		return spec->isEnabled (spec);
	else
		return spec->enabled;
}

extern bool enableXtag (xtagType type, bool state)
{
	bool old;
	xtagDefinition* spec = getXtagDefinition (type);

	Assert (spec);

	old = isXtagEnabled (type);
	spec->enabled = state;
	spec->isEnabled = NULL;

	return old;
}

extern bool isCommonXtag (xtagType type)
{
	return (type < XTAG_COUNT)? true: false;
}

extern int     getXtagOwner (xtagType type)
{
	return getXtagObject (type)->language;
}

const char* getXtagName (xtagType type)
{
	xtagDefinition* spec = getXtagDefinition (type);
	if (spec)
		return spec->name;
	else
		return NULL;
}

extern void initXtagObjects (void)
{
	xtagObject *xdesc;

	xtagObjectAllocated = ARRAY_SIZE (xtagDefinitions);
	xtagObjects = xMalloc (xtagObjectAllocated, xtagObject);

	for (int i = 0; i < ARRAY_SIZE (xtagDefinitions); i++)
	{
		xdesc = xtagObjects + i;
		xdesc->spec = xtagDefinitions + i;
		xdesc->language = LANG_IGNORE;
		xdesc->sibling = XTAG_UNKNOWN;
		xtagObjectUsed++;
	}
}

extern int countXtags (void)
{
	return xtagObjectUsed;
}

static void updateSiblingXtag (xtagType type, const char* name)
{
	int i;
	xtagObject *xdesc;

	for (i = type; i > 0; i--)
	{
		xdesc = xtagObjects + i - 1;
		if (xdesc->spec->name && (strcmp (xdesc->spec->name, name) == 0))
		{
			Assert (xdesc->sibling == XTAG_UNKNOWN);
			xdesc->sibling = type;
			break;
		}
	}
}

extern int defineXtag (xtagDefinition *spec, langType language)
{
	xtagObject *xdesc;
	size_t i;

	Assert (spec);
	Assert (spec->name);
	for (i = 0; i < strlen (spec->name); i++)
	{
		Assert ( isalnum (spec->name [i]) );
	}
	spec->letter = NUL_XTAG_LETTER;

	if (xtagObjectUsed == xtagObjectAllocated)
	{
		xtagObjectAllocated *= 2;
		xtagObjects = xRealloc (xtagObjects, xtagObjectAllocated, xtagObject);
	}
	xdesc = xtagObjects + (xtagObjectUsed);
	spec->xtype = xtagObjectUsed++;
	xdesc->spec = spec;
	xdesc->language = language;
	xdesc->sibling  = XTAG_UNKNOWN;

	updateSiblingXtag (spec->xtype, spec->name);
	return spec->xtype;
}

extern xtagType nextSiblingXtag (xtagType type)
{
	xtagObject *xdesc;

	xdesc = xtagObjects + type;
	return xdesc->sibling;
}
