/* A packrat parser generated by PackCC 1.6.0 */

#ifndef PCC_INCLUDED___PEG_ELM_H
#define PCC_INCLUDED___PEG_ELM_H

struct parserCtx;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct pelm_context_tag pelm_context_t;

pelm_context_t *pelm_create(struct parserCtx *auxil);
int pelm_parse(pelm_context_t *ctx, int *ret);
void pelm_destroy(pelm_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED___PEG_ELM_H */
