/* Automatically generated by misc/debuggen/rust.sh */

#ifndef CTAGS_PARSER_DEBUG_RUST_H
#define CTAGS_PARSER_DEBUG_RUST_H

#ifdef DO_TRACING
#include "vstring.h"

static const char *decodeTokenType(enum eTokenType e)
{ /* Generated by misc/enumstr.sh with cmdline:
     misc/enumstr.sh ./parsers/rust.c eTokenType decodeTokenType TOKEN_  */
	switch (e)
	{
		case     TOKEN_WHITESPACE: return "WHITESPACE";
		case         TOKEN_STRING: return "STRING";
		case          TOKEN_IDENT: return "IDENT";
		case         TOKEN_LSHIFT: return "LSHIFT";
		case         TOKEN_RSHIFT: return "RSHIFT";
		case         TOKEN_RARROW: return "RARROW";
		case            TOKEN_EOF: return "EOF";
		default:                   return "UNKNOWN";
	}
}


#endif /* DO_TRACING */
#endif /* CTAGS_PARSER_DEBUG_RUST_H */
