FILE <- TOKEN (_ TOKEN)* _*
TOKEN <- CLASS0 / CLASS1 / CLASS2 / CLASS3 / CLASS4 / CLASS5
CLASS0 <- 'a' [-]   { printf("CLASS0: '%s'\n", $0); }
CLASS1 <- 'b' [^-]  { printf("CLASS1: '%s'\n", $0); }
CLASS2 <- 'c' [-+]  { printf("CLASS2: '%s'\n", $0); }
CLASS3 <- 'd' [+-]  { printf("CLASS3: '%s'\n", $0); }
CLASS4 <- 'e' [^-+] { printf("CLASS4: '%s'\n", $0); }
CLASS5 <- 'f' [^+-] { printf("CLASS5: '%s'\n", $0); }
_ <- ' ' / '\n'
