.TH CTAGS 1 "Version 0.0.0" "Darren Hiebert" "Universal Ctags"


.SH "NAME"
ctags \- Generate tag files for source code

.SH
ABSTRACT

.SH SYNOPSIS
.TP 6
\fBctags\fP [\fBoptions\fP] [\fIfile(s)\fP]
.TP 6
\fBetags\fP [\fBoptions\fP] [\fIfile(s)\fP]


.SH "DESCRIPTION"
The \fBctags\fP and \fBetags\fP programs (hereinafter collectively referred to
as \fBctags\fP, except where distinguished) generate an index (or "tag") file
for a variety of language objects found in \fIfile(s)\fP.
This tag file allows these items to be quickly and easily located by a text
editor or other utility. A "tag" signifies a language object for which an
index entry is available (or, alternatively, the index entry created for that
object).

.SH
AUTHOR
.sp
The Developers.

.SS subsection1
.sp
This is the first subsection.

.SS "subsection2"
.sp
This is the second subsection.

.SS
subsection3
.sp
This is the third subsection.

.SS sub section 4
.sp
This is the fourth subsection.

.SS
sub section 5
.sp
This is the fifth subsection.

.SH
ACKNOWLEDGMENT
.sp

.SS
subsection6
.sp
This is the sixth subsection.

.SS
subsection7
.sp
This is the seventh subsection.

.SS "subsection8"
.sp
This is the eight subsection.

.SS subsection9
.sp
This is the ninth subsection.

.SS sub section 10
.sp
This is the tenth subsection.

.SS
sub section 11
.sp
This is the eleventh subsection.

.SH SEE ALSO
.sp
See tags(5) for the details of tags file format.

.SS
sub section 12
