#!/bin/sh
#
#
#  Copyright (c) 2014, Red Hat, Inc.
#  Copyright (c) 2014, Masatake YAMATO
#
#  Author: Masatake YAMATO <yamato@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.
#
#
# This is a xcmd driver for CoffeeTags.
# CoffeeTags is developed at https://github.com/lukaszkorecki/CoffeeTags .
#
#

if ! type coffeetags > /dev/null 2>&1; then
    exit 77
fi

case "$1" in
    --list-kinds*)
	coffeetags --list-kinds
	exit $?
	;;
    -*)
	echo "unknown option: $1" 1>&2
	exit 1
	;;
    *)
	coffeetags --include-vars "$1"
	exit $?
	;;
esac
