openapi: 3.0.0
info:
    title: test
    description: test
    version: '1.0'

servers:
  - url: http://example.com
    description: production

paths:
    /sample/path:
        get:
            summary: simple handler
            responses: {}

    /sample/other/path:
        get:
            responses: {}
        post:
            summary: xxx
            responses: {}

components:
    schemas:
        NullableField:
            type: object
            properties: {}
        NullableFieldStringEnum:
            type: object
            properties: {}

    parameters:
        CustomHeader:
            in: header
            name: X-Custom-Header
            required: false
            schema:
                type: string

    responses:
        Response1:
            description: Payment Required
            content:
                application/json:
                    schema:
                        type: object
                        properties: {}
        Response2:
            description: smth 2
            content:
                application/json:
                    schema:
                        type: object
                        properties: {}

tags:
  - name: android_handler
    description: Handler for Android clients
  - name: ios_handler
    description: Handler for iOS clients
