/*
 * Generated by ./misc/optlib2c from optlib/ctags-optlib.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"


static void initializeCtagsParser (parserDefinition *parser)
{
}

extern parserDefinition* CtagsParser (void)
{
	static const char *const extensions [] = {
		"ctags",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static const tagRegexTable const CtagsTagRegexTable [] = {
		{"^--langdef=([^ \\t]+)$", "\\1",
		"l,langdef", NULL},
		{"^--regex-[^=]+=.*\\/.,(.+)\\/.*", "\\1",
		"k,kind", NULL},
	};


	parserDefinition* const def = parserNew ("ctags");

	def->enabled       = TRUE;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->tagRegexTable = CtagsTagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(CtagsTagRegexTable);
	def->initialize    = initializeCtagsParser;

	return def;
}

/*
 * Editor modelines  -  https://www.wireshark.org/tools/modelines.html
 *
 * Local variables:
 * c-basic-offset: 4
 * tab-width: 4
 * End:
 *
 * vi: set shiftwidth=4 tabstop=4:
 * :indentSize=4:tabSize=4:
 */
