/*
 * Generated by ./misc/optlib2c from optlib/elm.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"


static void initializeElmParser (const langType language CTAGS_ATTR_UNUSED)
{
}

extern parserDefinition* ElmParser (void)
{
	static const char *const extensions [] = {
		"elm",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static tagRegexTable ElmTagRegexTable [] = {
		{"^(port[[:blank:]]+)?module[[:blank:]]+([[:upper:]][[:alnum:]_.]*)", "\\2",
		"m,module,Module", "{scope=push}{exclusive}"},
		{"^import[[:blank:]]+([[:alnum:]_.]+[[:blank:]]+as[[:blank:]]+.+)", "\\1",
		"i,import,Import", "{scope=clear}{exclusive}"},
		{"^import[[:blank:]]+([[:alnum:]_.]+)[[:blank:]]exposing", "\\1",
		"i,import,Import", "{scope=clear}{exclusive}"},
		{"^import[[:blank:]]+([[:alnum:]_.]+)", "\\1",
		"i,import,Import", "{scope=clear}{exclusive}"},
		{"^port[[:blank:]]+([[:lower:]][[:alnum:]_]*).*", "\\1",
		"p,port,Port", "{scope=clear}{exclusive}"},
		{"^type +([[:upper:]][[:alnum:]_]*.*)", "\\1",
		"t,type,Type Definition", "{scope=set}{exclusive}"},
		{"^[[:blank:]]+[|=][[:blank:]]+([[:upper:]][[:alnum:]_]*.*)$", "\\1",
		"c,constructor,Type Constructor", "{scope=ref}{exclusive}"},
		{"^type[[:blank:]]+alias[[:blank:]]+([[:upper:]][[:alnum:]_]*[[:blank:][:alnum:]_]*)", "\\1",
		"a,alias,Type Alias", "{scope=set}{exclusive}"},
		{"^([[:lower:]_][[:alnum:]_]*)[^=]*=$", "\\1",
		"f,function,Functions", "{scope=set}"},
		{"^[[:blank:]]+([[:lower:]_][[:alnum:]_]*)[^=]*=$", "\\1",
		"f,function,Functions", "{scope=ref}"},
	};


	parserDefinition* const def = parserNew ("elm");

	def->enabled       = true;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->tagRegexTable = ElmTagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(ElmTagRegexTable);
	def->initialize    = initializeElmParser;

	return def;
}
