/*
 * Generated by ./misc/optlib2c from optlib/kotlin.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"
#include "field.h"
#include "xtag.h"


static void initializeKotlinParser (const langType language)
{

	addLanguageRegexTable (language, "toplevel");
	addLanguageRegexTable (language, "comment");
	addLanguageRegexTable (language, "string");
	addLanguageRegexTable (language, "mlstring");
	addLanguageRegexTable (language, "vals");
	addLanguageRegexTable (language, "vars");

	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^/\\*",
	                               "", "", "{tenter=comment}", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^//[^\n]*\n",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^\"\"\"",
	                               "", "", "{tenter=mlstring}", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^\"",
	                               "", "", "{tenter=string}", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^'.{1,2}'",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^val\\s+\\(\\s*",
	                               "", "", "{tenter=vals}", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^var\\s+\\(\\s*",
	                               "", "", "{tenter=vars}", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^class\\s+([[:alnum:]_]+)",
	                               "\\1", "c", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^interface\\s+([[:alnum:]_]+)",
	                               "\\1", "i", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^object\\s+([[:alnum:]_]+)",
	                               "\\1", "o", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^typealias\\s+([[:alnum:]_]+)",
	                               "\\1", "T", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^fun(<.*>)*\\s+([[:alnum:]_]+\\.)*([[:alnum:]_]+)",
	                               "\\3", "m", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^val\\s+([[:alnum:]_]+\\.)*([[:alnum:]_]+)",
	                               "\\2", "C", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^var\\s+([[:alnum:]_]+\\.)*([[:alnum:]_]+)",
	                               "\\2", "v", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^[[:alnum:]]+",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "toplevel",
	                               "^.",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "comment",
	                               "^\\*/",
	                               "", "", "{tleave}", NULL);
	addLanguageTagMultiTableRegex (language, "comment",
	                               "^[^*]+",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "comment",
	                               "^.",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "string",
	                               "^[^\\\\\"]+",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "string",
	                               "^\\\\.",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "string",
	                               "^\"",
	                               "", "", "{tleave}", NULL);
	addLanguageTagMultiTableRegex (language, "string",
	                               "^.",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "mlstring",
	                               "^\"\"\"",
	                               "", "", "{tleave}", NULL);
	addLanguageTagMultiTableRegex (language, "mlstring",
	                               "^[^\\\\\"]+",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "mlstring",
	                               "^.",
	                               "", "", "", NULL);
	addLanguageTagMultiTableRegex (language, "vals",
	                               "^([[:alnum:]_]+)\\s*(:\\s*[[:alnum:]_]+)*\\s*,*\\s*",
	                               "\\1", "C", "", NULL);
	addLanguageTagMultiTableRegex (language, "vals",
	                               "^\\)",
	                               "", "", "{tleave}", NULL);
	addLanguageTagMultiTableRegex (language, "vars",
	                               "^([[:alnum:]_]+)\\s*(:\\s*[[:alnum:]_]+)*\\s*,*\\s*",
	                               "\\1", "v", "", NULL);
	addLanguageTagMultiTableRegex (language, "vars",
	                               "^\\)",
	                               "", "", "{tleave}", NULL);
}

extern parserDefinition* KotlinParser (void)
{
	static const char *const extensions [] = {
		"kt",
		"kts",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static kindDefinition KotlinKindTable [] = {
		{
		  true, 'c', "class", "classes",
		},
		{
		  true, 'o', "object", "objects",
		},
		{
		  true, 'i', "interface", "interfaces",
		},
		{
		  true, 'T', "typealias", "typealiases",
		},
		{
		  true, 'm', "method", "methods",
		},
		{
		  true, 'C', "constant", "constants",
		},
		{
		  true, 'v', "variable", "variables",
		},
	};

	parserDefinition* const def = parserNew ("Kotlin");

	def->enabled       = true;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->kindTable     = KotlinKindTable;
	def->kindCount     = ARRAY_SIZE(KotlinKindTable);
	def->initialize    = initializeKotlinParser;

	return def;
}
