/*
 * Generated by ./misc/optlib2c from optlib/m4.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"


static void initializeM4Parser (const langType language)
{
	enableRegexKind (language, 'I', FALSE);
}

extern parserDefinition* M4Parser (void)
{
	static const char *const extensions [] = {
		"m4",
		"spt",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static tagRegexTable M4TagRegexTable [] = {
		{"^dnl.*$", "",
		"", "{exclusive}"},
		{"^[[:space:]]*(m4_)?define\\(([[`{]|<<)?([^]'}>,]+)([]'}]|>>)?,", "\\3",
		"d,definition", "{exclusive}"},
		{"^[[:space:]]*(m4_)?undefine\\([[`]?([^]'),]+)[]']?[),]", "\\2",
		"u,undefinition", "{exclusive}"},
		{"^[[:space:]]*(m4_)?s?include\\([[`]?([^]')]+)[]']?\\)", "\\2",
		"I,inclusion", "{exclusive}"},
	};


	parserDefinition* const def = parserNew ("m4");

	def->enabled       = FALSE;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->tagRegexTable = M4TagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(M4TagRegexTable);
	def->initialize    = initializeM4Parser;

	return def;
}
