/*
 * Generated by ./misc/optlib2c from optlib/nftables.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"
#include "field.h"
#include "xtag.h"


static void initializeNftablesParser (const langType language CTAGS_ATTR_UNUSED)
{
}

extern parserDefinition* NftablesParser (void)
{
	static const char *const extensions [] = {
		"nft",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static roleDefinition NftablesFamilyRoleTable [] = {
		{ false, "referenced", "referenced somehow" },
	};
	static roleDefinition NftablesRulesetRoleTable [] = {
		{ true, "included", "included ruleset" },
	};
	static kindDefinition NftablesKindTable [] = {
		{
		  true, 'f', "family", "families",
		  ATTACH_ROLES(NftablesFamilyRoleTable),
		},
		{
		  true, 'h', "hook", "hooks",
		},
		{
		  true, 't', "table", "tables",
		},
		{
		  true, 'c', "chain", "chains",
		},
		{
		  true, 's', "set", "sets",
		},
		{
		  true, 'm', "map", "maps",
		},
		{
		  true, 'D', "definition", "definitions",
		},
		{
		  true, 'R', "ruleset", "rulesets",
		  ATTACH_ROLES(NftablesRulesetRoleTable),
		},
		{
		  true, 'H', "ctherlper", "connection tracking helpers",
		},
		{
		  true, 'E', "ctexpectation", "connection tracking expectations",
		},
		{
		  true, 'T', "cttimeout", "connection tracking timeout",
		},
		{
		  true, 'S', "secmark", "secmarks",
		},
		{
		  true, 'W', "flowtable", "flowtables",
		},
		{
		  true, 'P', "synproxy", "synproxies",
		},
		{
		  true, 'C', "counter", "counters",
		},
		{
		  true, 'l', "limit", "limits",
		},
		{
		  true, 'Q', "quota", "quotas",
		},
	};
	static tagRegexTable NftablesTagRegexTable [] = {
		{"^[ \t]*#", "",
		"", "{exclusive}", NULL, false},
		{"^[ \t]*family[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"f", "{exclusive}{scope=set}", NULL, false},
		{"^[ \t]*hook[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"h", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*table[ \t]+([-a-zA-Z0-9_]+)[ \t]+([a-zA-Z0-9_]+)[ \t]*\\{", "",
		"", "{exclusive}"
		"{{\n"
		"   \\1 /family /referenced _reftag _commit\n"
		"   \\2 /table _tag _commit dup 3 -1 roll scope:\n"
		"   _scopeset\n"
		"}}", NULL, false},
		{"^[ \t]*table[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"t", "{exclusive}{scope=set}", NULL, false},
		{"^[ \t]*chain[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"c", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*set[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"s", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*map[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"m", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*define[ \t]+([-a-zA-Z0-9_]+)[ \t]*=", "\\1",
		"D", "{exclusive}", NULL, false},
		{"^[ \t]*include[ \t]+\"([^\"]+)\"", "\\1",
		"R", "{exclusive}{_role=included}", NULL, false},
		{"^[ \t]*ct[ \t]+helper[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"H", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*ct[ \t]+expectation[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"E", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*ct[ \t]+timeout[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"T", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*secmark[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"S", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*flowtable[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"W", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*synproxy[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"P", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*counter[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"C", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*limit[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"L", "{exclusive}{scope=ref}", NULL, false},
		{"^[ \t]*quota[ \t]+([-a-zA-Z0-9_]+)[ \t]*\\{", "\\1",
		"Q", "{exclusive}{scope=ref}", NULL, false},
	};


	parserDefinition* const def = parserNew ("Nftables");

	def->versionCurrent= 0;
	def->versionAge    = 0;
	def->enabled       = true;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->useCork       = CORK_QUEUE;
	def->kindTable     = NftablesKindTable;
	def->kindCount     = ARRAY_SIZE(NftablesKindTable);
	def->tagRegexTable = NftablesTagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(NftablesTagRegexTable);
	def->initialize    = initializeNftablesParser;

	return def;
}
