name: cross compile for Android on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        build-machine-os: [macos-15, macos-14, macos-26]

    runs-on: ${{ matrix.build-machine-os }}

    steps:
      - uses: actions/checkout@v7

      - run: brew install make automake autoconf

      - run: ./autogen.sh

      - name: Run ./configure ...
        run: |
          TOOLCHAIN_BASE_DIR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64
          TOOLCHAIN_BIN_DIR=$TOOLCHAIN_BASE_DIR/bin
          SYSROOT=$TOOLCHAIN_BASE_DIR/sysroot

          ln -s "$TOOLCHAIN_BIN_DIR/llvm-readelf" llvm-readelf

          export CC=$TOOLCHAIN_BIN_DIR/aarch64-linux-android24-clang
          export AR=$TOOLCHAIN_BIN_DIR/llvm-ar
          export RANLIB=$TOOLCHAIN_BIN_DIR/llvm-ranlib

          export CFLAGS="--sysroot $SYSROOT -Qunused-arguments -Os -fpic"
          export CPPFLAGS="--sysroot $SYSROOT -Qunused-arguments"
          export LDFLAGS="--sysroot $SYSROOT"

          ./configure \
              --host=aarch64-linux-android \
              --disable-iconv \
              --disable-xml \
              --disable-json \
              --disable-yaml \
              --disable-pcre2

      - run: make V=1

      - run: ./llvm-readelf -h ctags

      # https://www.sco.com/developers/gabi/latest/ch4.eheader.html
      - run: test "$(hexdump -n 20 -e '20/1 "%02X" "\n"' ctags)" = '7F454C460201010000000000000000000300B700'
